---
title: Domain Model
---
classDiagram
    class Gym {
        -string name
        -Address address
        -string phone
    }

    class Address {
        <<DataType>>
        +string street
        +string city
        +string postalCode
    }

    Gym ..> Address
